/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author afmontanar
 */
public class DetallePagos extends javax.swing.JDialog {

    private utilities.ModelosTablaS modelot;
    private int s;
    /**
     * Creates new form GrillaChofer
     */
    public DetallePagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        String n[] = {"Identificacion","Nombres","Apellidos","Direccion","Celular","Detalle","clienteid"};
        this.modelot = new utilities.ModelosTablaS(n, jTable1);
        jTable1.setModel(this.modelot);
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 840, 340));

        jLabel1.setText("Pagos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        nombre1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        nombre1.setName("nombre"); // NOI18N
        jPanel1.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 40));

        nombre2.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Cliente"));
        nombre2.setName("nombre"); // NOI18N
        jPanel1.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 40));

        jButton1.setText("Ver abono a realizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            if(this.s==0){
                this.mandarDatosHv();
                this.setVisible(false);
            }else if(this.s==1){
                this.mandarDatosBhv();
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        verDetalleAbonoRealizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    // End of variables declaration//GEN-END:variables

    void alimentarGrillaChofer(String toString, int s) {
        this.s = s;
        this.modelot.vaciarTabla();
        try {
            ResultSet MysqlConsulta = Prestamos.o.MysqlConsulta("SELECT * FROM `chofer` where clienteid = '"+toString+"'");
            while(MysqlConsulta.next()){
                String d[]={MysqlConsulta.getString("Identificacion"), MysqlConsulta.getString("Nombres"),MysqlConsulta.getString("Apellidos"),MysqlConsulta.getString("Direccion"),MysqlConsulta.getString("Celular"),  MysqlConsulta.getString("Detalle"),MysqlConsulta.getString("clienteid")};
                this.modelot.ingresarUsuarioM(d);
            }
        this.modelot.reload();
        } catch (SQLException ex) {
            Logger.getLogger(GrillaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void llenarTabla() {
         this.modelot.vaciarTabla();
        try {
            ResultSet MysqlConsulta = Prestamos.o.MysqlConsulta("SELECT * FROM `cliente`");
            while(MysqlConsulta.next()){
                String d[]={MysqlConsulta.getString("tipoid"), MysqlConsulta.getString("idcliente"),MysqlConsulta.getString("nombre"),MysqlConsulta.getString("apellido"),MysqlConsulta.getString("apodo"),  MysqlConsulta.getString("direccion")};
                this.modelot.ingresarUsuarioM(d);
            }
        this.modelot.reload();
        } catch (SQLException ex) {
            Logger.getLogger(GrillaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mandarDatosHv() {
         int selectedRow = jTable1.getSelectedRow();
         Principal parent = (Principal) super.getParent();
         parent.gChoferAhv(jTable1.getValueAt(selectedRow, 0)+"",jTable1.getValueAt(selectedRow, 1)+"");
    }

    private void mandarDatosBhv() {
         int selectedRow = jTable1.getSelectedRow();
         Principal parent = (Principal) super.getParent();
         parent.gChoferABhv(jTable1.getValueAt(selectedRow, 0)+"",jTable1.getValueAt(selectedRow, 1)+"");
    }

    void alimentarHv(String idCliente) {
        this.modelot.vaciarTabla();
        try {
            ResultSet MysqlConsulta = Prestamos.o.MysqlConsulta("SELECT * FROM `pagos` where idCliente = '"+idCliente+"'");
            while(MysqlConsulta.next()){
                String d[]={MysqlConsulta.getString("pagodelDia"), MysqlConsulta.getString("fecha"),MysqlConsulta.getString("detalle"),MysqlConsulta.getString("numeroPago")};
                this.modelot.ingresarUsuarioM(d);
            }
        this.modelot.reload();
        } catch (SQLException ex) {
            Logger.getLogger(GrillaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verDetalleAbonoRealizar() {
        Principal parent = (Principal) super.getParent();
        parent.();
    }
    
}
